/* The one icon mapping: StudyHub icon name -> Phosphor icon name (the Light weight, MIT). ui/components/icon-paths.js is made from it:
     node scripts/icons/build-icons.mjs           print what would be written
     node scripts/icons/build-icons.mjs --write   rewrite ui/components/icon-paths.js (after editing the map or upgrading @phosphor-icons/core)
   tests/icon-paths.test.mjs fails when the committed module differs from what this makes from node_modules/@phosphor-icons/core.
   The StudyHub brand marks are not Phosphor: they stay hand-drawn in ui/components/Icon.jsx. */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
export const OUTPUT = join(root, 'ui', 'components', 'icon-paths.js');
const PHOSPHOR = join(root, 'node_modules', '@phosphor-icons', 'core');

/* Our name -> Phosphor name. Every name the app asks <Icon> for is here; the arrows that CSS turns (chevron, caret) point right. */
export const ICON_MAP = {
  check: 'check',
  close: 'x',
  plus: 'plus',
  minus: 'minus',
  upload: 'upload-simple',
  download: 'download-simple',
  file: 'file-text',
  audio: 'music-notes',
  sparkle: 'sparkle',
  info: 'info',
  success: 'check-circle',
  warning: 'warning',
  error: 'warning-circle',
  external: 'arrow-square-out',
  chevron: 'caret-right',
  'chevron-left': 'caret-left',
  'chevron-down': 'caret-down',
  caret: 'caret-right',
  fit: 'frame-corners',
  play: 'play',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  key: 'key',
  refresh: 'arrow-clockwise',
  folder: 'folder',
  help: 'question',
  'thumb-up': 'thumbs-up',
  'thumb-down': 'thumbs-down',
  list: 'list-bullets',
  search: 'magnifying-glass',
  type: 'text-aa',
  panel: 'sidebar-simple',
  model: 'cpu',
  mail: 'envelope-simple',
  more: 'dots-three',
  calendar: 'calendar-blank',
  filter: 'funnel-simple',
  edit: 'pencil-simple',
  trash: 'trash',
  archive: 'archive',
  link: 'link',
  checklist: 'list-checks',
  move: 'arrow-line-right',
  sync: 'arrows-clockwise',
  undo: 'arrow-u-up-left',
  clock: 'clock',
  copy: 'copy',
  book: 'book-open',
  settings: 'gear-six',
  // The sidebar rail: one mark per destination.
  'nav-audio': 'file-audio',
  'nav-live': 'microphone',
  'nav-workflows': 'flow-arrow',
  'nav-coach': 'sparkle',
  'nav-resume': 'arrow-bend-up-left',
  'nav-library': 'books',
  'nav-sources': 'files',
  'nav-generate': 'plus',
  'nav-tasks': 'list-dashes',
  'nav-skeleton': 'graph',
  'nav-dashboard': 'chart-bar',
  'nav-exam': 'exam',
  'nav-wrongbook': 'arrow-counter-clockwise',
  'nav-notes': 'notebook',
  'nav-board': 'kanban',
  'nav-settings': 'sliders-horizontal',
  'nav-auto': 'circle-half',
  'nav-dark': 'moon',
  'nav-language': 'globe',
  'nav-light': 'sun',
  'nav-tour': 'compass',
};

const attr = (tag, name) => new RegExp(`\\s${name}="([^"]*)"`).exec(tag)?.[1];

/** The `d` of every <path> of a Phosphor SVG; fails loudly on anything a single fill path list cannot draw. */
export function pathsOfSvg(svg, name) {
  if (!/viewBox="0 0 256 256"/.test(svg)) throw new Error(`${name}: not a 256 grid svg`);
  const shapes = [...svg.matchAll(/<(?!svg\b|\/svg)([a-z]+)\b([^>]*)\/?>/g)];
  if (!shapes.length) throw new Error(`${name}: no shapes`);
  return shapes.map(([, tag, rest]) => {
    if (tag !== 'path') throw new Error(`${name}: unexpected <${tag}>`);
    if (/\sopacity=/.test(rest)) throw new Error(`${name}: has an opacity layer`);
    const d = attr(rest, 'd');
    if (!d) throw new Error(`${name}: path without d`);
    return d;
  });
}

/** The text of ui/components/icon-paths.js, made from the installed @phosphor-icons/core. */
export async function iconPathsModule() {
  const pkg = JSON.parse(await readFile(join(PHOSPHOR, 'package.json'), 'utf8'));
  const dir = join(PHOSPHOR, 'assets', 'light');
  const rows = [];
  for (const [name, phosphor] of Object.entries(ICON_MAP)) {
    const paths = pathsOfSvg(await readFile(join(dir, `${phosphor}-light.svg`), 'utf8'), phosphor);
    const key = /^[a-z]+$/.test(name) ? name : JSON.stringify(name);
    rows.push(`  ${key}: ${paths.length === 1 ? JSON.stringify(paths[0]) : JSON.stringify(paths)},`);
  }
  return `/* Generated by scripts/icons/build-icons.mjs from @phosphor-icons/core ${pkg.version} (Light weight): the path data of the icons the app uses, on a 256 grid.
   Do not edit; change the map in the script and run node scripts/icons/build-icons.mjs --write.
   Phosphor Icons, Copyright (c) 2023 Phosphor Icons, MIT License: https://github.com/phosphor-icons/core/blob/main/LICENSE
   A string is one path; an array is several paths of one icon. */
export const ICON_PATHS = {
${rows.join('\n')}
};
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const text = await iconPathsModule();
  if (process.argv.includes('--write')) {
    await writeFile(OUTPUT, text);
    console.log(`wrote ${OUTPUT} (${Object.keys(ICON_MAP).length} icons, ${text.length} bytes)`);
  } else {
    console.log(`${Object.keys(ICON_MAP).length} icons, ${text.length} bytes (run with --write to rewrite ${OUTPUT})`);
  }
}
