/* The pdf.js assets of the page peek (ui/document-preview/peek/pdf-assets.js says why) as plain JS modules, so every bundler (the DSH
   client build, the preview, the tests) takes them without a loader and splits them into chunks of their own:
     node scripts/pdf-assets.mjs           print what would be written (sizes)
     node scripts/pdf-assets.mjs --write   rewrite ui/document-preview/peek/assets/ (after upgrading pdfjs-dist)
   tests/page-peek-assets.test.mjs fails when the committed modules differ from what this makes from node_modules/pdfjs-dist. */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CMAP_GROUPS, FONT_FILES, WASM_FILES, cmapGroup, shipsCMap } from '../ui/document-preview/peek/pdf-assets.js';

const root = fileURLToPath(new URL('../', import.meta.url));
export const ASSETS_DIR = join(root, 'ui', 'document-preview', 'peek', 'assets');

const LICENSES = {
  wasm: 'jbig2.wasm: PDFium (BSD-3-Clause) and pdf.js (Apache-2.0); openjpeg.wasm: OpenJPEG (BSD-2-Clause) and pdf.js (Apache-2.0)',
  fonts: 'Foxit fonts from PDFium (BSD-3-Clause)',
  cmaps: 'Adobe CMap resources (BSD-3-Clause, Copyright Adobe Systems Incorporated)',
};

const header = (version, what, license) => `/* Generated by scripts/pdf-assets.mjs from pdfjs-dist ${version}: ${what}. Do not edit; run node scripts/pdf-assets.mjs --write.\n   ${license} */\n`;
const b64 = bytes => Buffer.from(bytes).toString('base64');

/** Map of module file name -> module text, made from the installed pdfjs-dist. */
export async function assetModules() {
  const pdfjs = dirname(createRequire(import.meta.url).resolve('pdfjs-dist/package.json'));
  const { version } = JSON.parse(await readFile(join(pdfjs, 'package.json'), 'utf8'));
  const modules = new Map();
  for (const [file, name] of Object.entries(WASM_FILES)) {
    modules.set(`wasm-${name}.js`, `${header(version, `wasm/${file}`, LICENSES.wasm)}export default ${JSON.stringify(b64(await readFile(join(pdfjs, 'wasm', file))))};\n`);
  }
  const fonts = {};
  for (const file of FONT_FILES) fonts[file] = b64(await readFile(join(pdfjs, 'standard_fonts', file)));
  modules.set('fonts.js', `${header(version, 'standard_fonts/ (Symbol and ZapfDingbats)', LICENSES.fonts)}export default ${JSON.stringify(fonts)};\n`);
  const names = (await readdir(join(pdfjs, 'cmaps'))).filter(file => file.endsWith('.bcmap')).map(file => basename(file, '.bcmap')).filter(shipsCMap).sort();
  for (const group of CMAP_GROUPS) {
    const maps = {};
    for (const name of names.filter(name => cmapGroup(name) === group)) maps[name] = b64(await readFile(join(pdfjs, 'cmaps', `${name}.bcmap`)));
    modules.set(`cmaps-${group}.js`, `${header(version, `cmaps/ (${group})`, LICENSES.cmaps)}export default ${JSON.stringify(maps)};\n`);
  }
  return modules;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const modules = await assetModules();
  const write = process.argv.includes('--write');
  if (write) {
    await mkdir(ASSETS_DIR, { recursive: true });
    for (const file of await readdir(ASSETS_DIR)) if (!modules.has(file)) await rm(join(ASSETS_DIR, file));
  }
  let total = 0;
  for (const [file, text] of modules) {
    total += Buffer.byteLength(text);
    if (write) await writeFile(join(ASSETS_DIR, file), text);
    console.log(`${write ? 'wrote' : 'would write'} ${file} ${Buffer.byteLength(text)} bytes`);
  }
  console.log(`${modules.size} modules, ${total} bytes`);
}
